# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: mohsin.magnificgallery::lang.magnific.name

# Model Form Field configuration
form: ~/plugins/mohsin/magnificgallery/models/gallery/fields.yaml

# Model Class name
modelClass: Mohsin\MagnificGallery\Models\Gallery

# Default redirect location
defaultRedirect: mohsin/magnificgallery/galleries

create:
    title: mohsin.magnificgallery::lang.galleries.create_galleries
    redirect: mohsin/magnificgallery/galleries/update/:id
    redirectClose: mohsin/magnificgallery/galleries

update:
    title: mohsin.magnificgallery::lang.galleries.update_galleries
    redirect: mohsin/magnificgallery/galleries
    redirectClose: mohsin/magnificgallery/galleries
